// Income/Expense only - used anywhere "Transfer" wouldn't make sense: a
// category's own type (there's only ever one system Transfer category, not
// user-creatable), a recurring transaction's type (transfers are one-off,
// not scheduled), and the "default transaction type" setting (defaulting
// straight into Transfer mode isn't a sensible everyday default).
export const CoreTransactionType = [
  {
    id: 2,
    label: 'Income',
  },
  {
    id: 1,
    label: 'Expense',
  },
];

// Full set for the actual Add/Edit Transaction screen only.
export const TransactionType = [...CoreTransactionType, { id: 3, label: 'Transfer' }];

export const genders = [
  {
    id: 1,
    label: 'Female',
  },
  {
    id: 2,
    label: 'Male',
  },
  {
    id: 3,
    label: 'Others',
  },
];

export const materialIconList: { [index: string]: string[] } = {
  Entertainment: [
    'sports-esports',
    'movie',
    'music-note',
    'event',
    'live-tv',
    'theaters',
    'local-bar',
    'nightlife',
    'celebration',
    'mic',
    'subscriptions',
    'headphones',
    'casino',
    'sports-bar',
    'stadium',
    'festival',
    'toys',
  ],
  Finance: [
    'account-balance-wallet',
    'account-balance',
    'credit-card',
    'attach-money',
    'request-quote',
    'savings',
    'payments',
    'price-change',
    'price-check',
    'calculate',
    'trending-up',
    'currency-exchange',
    'monetization-on',
    'paid',
    'pie-chart',
  ],
  Food: [
    'restaurant',
    'local-dining',
    'fastfood',
    'icecream',
    'cake',
    'brunch-dining',
    'local-bar',
    'local-cafe',
    'dining',
    'takeout-dining',
    'local-grocery-store',
    'ramen-dining',
    'liquor',
    'bakery-dining',
    'set-meal',
    'lunch-dining',
    'coffee',
  ],
  General: [
    'category',
    'notes',
    'settings',
    'info',
    'edit',
    'delete',
    'help',
    'warning',
    'security',
    'dashboard',
    'label',
    'more-horiz',
    'apps',
    'star',
    'bookmark',
    'flag',
  ],
  Medical: [
    'local-hospital',
    'medication',
    'medical-information',
    'healing',
    'monitor-heart',
    'masks',
    'local-pharmacy',
    'vaccines',
    'sick',
    'personal-injury',
    'pets',
    'psychology',
    'spa',
    'fitness-center',
    'accessible',
    'coronavirus',
    'medical-services',
  ],
  Shopping: [
    'shopping-cart',
    'store',
    'storefront',
    'loyalty',
    'shopping-bag',
    'local-mall',
    'local-offer',
    'card-giftcard',
    'qr-code-scanner',
    'payment',
    'checkroom',
    'diamond',
    'sell',
    'inventory',
    'add-shopping-cart',
    'local-shipping',
  ],
  'People and Art': [
    'person',
    'group',
    'diversity-3',
    'face',
    'support-agent',
    'supervisor-account',
    'contacts',
    'child-care',
    'elderly',
    'volunteer-activism',
    'palette',
    'brush',
    'color-lens',
    'style',
    'edit-note',
    'animation',
    'gradient',
    'wallpaper',
    'design-services',
    'emoji-emotions',
    'theater-comedy',
    'photo-camera',
  ],
  Travel: [
    'flight',
    'hotel',
    'commute',
    'beach-access',
    'hiking',
    'luggage',
    'map',
    'directions-car',
    'train',
    'departure-board',
    'airplane-ticket',
    'location-on',
    'directions-boat',
    'terrain',
    'explore',
    'travel-explore',
    'car-rental',
    'tour',
  ],
  Bills: [
    'receipt-long',
    'receipt',
    'fact-check',
    'request-quote',
    'description',
    'payments',
    'attach-file',
    'assignment',
    'event-repeat',
    'schedule-send',
    'paid',
    'toll',
  ],
  Utilities: [
    'lightbulb',
    'power',
    'water',
    'wifi',
    'router',
    'cable',
    'thermostat',
    'gas-meter',
    'solar-power',
    'battery-charging-full',
    'ac-unit',
    'local-fire-department',
    'plumbing',
    'electrical-services',
    'propane',
    'wind-power',
  ],
  Education: [
    'school',
    'menu-book',
    'auto-stories',
    'book',
    'backpack',
    'calculate',
    'science',
    'laptop-chromebook',
    'library-books',
    'draw',
    'quiz',
    'history-edu',
    'functions',
    'biotech',
    'translate',
  ],
  Work: [
    'work',
    'business-center',
    'engineering',
    'badge',
    'task-alt',
    'schedule',
    'meeting-room',
    'event-note',
    'laptop',
    'groups',
    'assignment-turned-in',
    'business',
    'corporate-fare',
    'handshake',
  ],
  Transportation: [
    'directions-car',
    'directions-bus',
    'directions-bike',
    'commute',
    'electric-scooter',
    'train',
    'two-wheeler',
    'local-taxi',
    'pedal-bike',
    'airport-shuttle',
    'directions-subway',
    'directions-boat',
    'ev-station',
    'local-gas-station',
    'traffic',
    'toll',
  ],
  Gifts: [
    'redeem',
    'card-giftcard',
    'loyalty',
    'volunteer-activism',
    'sentiment-satisfied',
    'celebration',
    'cake',
    'favorite',
    'auto-awesome',
    'star',
    'diamond',
  ],
  Home: [
    'home',
    'weekend',
    'chair',
    'roofing',
    'kitchen',
    'bed',
    'bathroom',
    'light',
    'sensor-door',
    'foundation',
    'yard',
    'countertops',
    'window',
    'garage',
    'stairs',
    'deck',
  ],
  Subscriptions: [
    'subscriptions',
    'smart-display',
    'stream',
    'tv',
    'video-library',
    'live-tv',
    'auto-awesome',
    'alarm-on',
    'podcasts',
    'headset',
    'sports-esports',
    'newspaper',
    'radio',
  ],
  Pets: ['pets', 'cruelty-free', 'park', 'set-meal', 'nature', 'directions-walk'],
  'Fitness and Sports': [
    'fitness-center',
    'sports-soccer',
    'sports-basketball',
    'sports-tennis',
    'self-improvement',
    'directions-run',
    'pool',
    'sports-volleyball',
    'sports-golf',
    'hiking',
  ],
  Insurance: [
    'shield',
    'verified-user',
    'health-and-safety',
    'gavel',
    'policy',
    'umbrella',
    'local-police',
  ],
  'Beauty and Personal Care': [
    'spa',
    'face-retouching-natural',
    'content-cut',
    'dry-cleaning',
    'clean-hands',
    'shower',
    'soap',
  ],
};

export const customColors = [
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Sunset Orange', hex: '#FF7F50' },
  { name: 'Royal Purple', hex: '#7851A9' },
  { name: 'Deep Pink', hex: '#FF1493' },
  { name: 'Goldenrod', hex: '#DAA520' },
  { name: 'Coral', hex: '#FF6F61' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Sea Green', hex: '#2E8B57' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Rose Gold', hex: '#B76E79' },
  { name: 'Indigo Blue', hex: '#4F46E5' },
  { name: 'Coral Red', hex: '#FF6B6B' },
  { name: 'Emerald Green', hex: '#068836' },
  { name: 'Rose Red', hex: '#E63946' },
  { name: 'Green', hex: '#4CAF50' },
  { name: 'Purple', hex: '#7B61FF' },
  { name: 'Rose normal', hex: '#F472B6' },
  { name: 'Green light', hex: '#22C55E' },
  { name: 'Electric Indigo', hex: '#6F00FF' },
  { name: 'Flamingo Pink', hex: '#FC6C85' },
  { name: 'Vermilion', hex: '#E34234' },
  { name: 'Tangerine', hex: '#F28500' },
  { name: 'Plum', hex: '#8E4585' },
  { name: 'Electric Purple', hex: '#BF00FF' },
  { name: 'Bright Teal', hex: '#00BFA6' },
  { name: 'Hot Magenta', hex: '#FF1DCE' },
  { name: 'Persian Green', hex: '#00A693' },
  { name: 'Pumpkin', hex: '#FF7518' },
  { name: 'Fire Red', hex: '#FF2400' },
  { name: 'Sapphire Blue', hex: '#0F52BA' },
  { name: 'Cosmic Purple', hex: '#5D3FD3' },
  { name: 'Cerulean', hex: '#0EA5E9' },
  { name: 'Lavender', hex: '#A78BFA' },
  { name: 'Mustard', hex: '#D4A017' },
  { name: 'Terracotta', hex: '#C7623D' },
  { name: 'Cobalt', hex: '#1E5FE0' },
  { name: 'Magenta', hex: '#D6249F' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Periwinkle', hex: '#7C83FD' },
  { name: 'Copper', hex: '#B87333' },
  { name: 'Jade', hex: '#00A86B' },
  { name: 'Raspberry', hex: '#E0115F' },
  { name: 'Ochre', hex: '#CC9A2E' },
  { name: 'Denim', hex: '#3B6DBF' },
  { name: 'Lilac', hex: '#C8A2C8' },
  { name: 'Amethyst', hex: '#9966CC' },
  { name: 'Watermelon', hex: '#FC4C4E' },
  { name: 'Cerise', hex: '#DE3163' },
  { name: 'Teal Blue', hex: '#1CA9C9' },
];

export const accountIcon = [
  'attach-money',
  'account-balance',
  'account-balance-wallet',
  'account-circle',
  'person',
  'person-outline',
  'credit-card',
  'savings',
  'wallet-giftcard',
  'payments',
  'local-atm',
  'currency-bitcoin',
  'currency-exchange',
  'add-card',
  'card-travel',
  'account-box',
  'manage-accounts',
  'money',
];

export const exportType = [
  {
    id: 'pdf',
    label: 'pdf',
  },
  {
    id: 'xlsx',
    label: 'xlsx',
  },
  {
    id: 'csv',
    label: 'csv',
  },
];
export const transactionExportType = [
  {
    id: 'all',
    label: 'All',
  },
  {
    id: 'income',
    label: 'Income',
  },
  {
    id: 'expense',
    label: 'Expense',
  },
  {
    id: 'transfer',
    label: 'Transfer',
  },
];

export const currencyOptions = [
  { id: '₹', label: '₹' },
  { id: '$', label: '$' },
  { id: '€', label: '€' },
  { id: '£', label: '£' },
  { id: '¥', label: '¥' },
];

export const dataGroupingType = [
  {
    id: 'daily',
    label: 'Daily',
  },
  {
    id: 'weekly',
    label: 'Weekly',
  },
  {
    id: 'monthly',
    label: 'Monthly',
  },
  // {
  //   id: 'year',
  //   label: 'Year',
  // },
];

export const recurringFrequencyType = [
  {
    id: 'daily',
    label: 'Daily',
  },
  {
    id: 'weekly',
    label: 'Weekly',
  },
  {
    id: 'monthly',
    label: 'Monthly',
  },
  {
    id: 'yearly',
    label: 'Yearly',
  },
];

export const debtDirectionType = [
  {
    id: 'owed_to_me',
    label: 'They owe me',
  },
  {
    id: 'owed_by_me',
    label: 'I owe them',
  },
];

// Shared across the various "jump to a month/year" quick-pick UIs (dashboard
// month switcher, date pickers) so a calendar full month grid isn't the only
// way to reach a far-off date.
export const MONTH_LABELS = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
