export const interestList = [
  // { key: 1, value: '1%' },
  // { key: 2, value: '2%' },
  // { key: 3, value: '3%' },
  // { key: 4, value: '4%' },
  // { key: 5, value: '5%' },
  // { key: 6, value: '6%' },
  // { key: 7, value: '7%' },
  // { key: 8, value: '8%' },
  // { key: 9, value: '9%' },
  // { key: 10, value: '10%' },
  { key: 11, value: '11%' },
  { key: 12, value: '12%' },
  { key: 13, value: '13%' },
  { key: 14, value: '14%' },
  { key: 15, value: '15%' },
  { key: 16, value: '16%' },
  { key: 17, value: '17%' },
  { key: 18, value: '18%' },
  { key: 19, value: '19%' },
  { key: 20, value: '20%' },
];

export const TransactionType = [
  {
    id: 2,
    label: 'Income',
  },
  {
    id: 1,
    label: 'Expense',
  },
];

export const paymentTypes = [
  {
    key: 1,
    value: 'Interest Only',
  },
  {
    key: 2,
    value: 'Principle with Interest',
  },
];

export const suretyType = [
  {
    key: 1,
    value: 'Document',
  },
  {
    key: 2,
    value: 'Gold',
  },
  {
    key: 3,
    value: 'Others',
  },
];

export const genders = [
  {
    id: 1,
    label: 'Female',
  },
  {
    id: 2,
    label: 'Male',
  },
  {
    id: 3,
    label: 'Others',
  },
];

export const accounts = [
  {
    exp_ba_id: 1,
    exp_ba_user_id: 1,
    exp_ba_name: 'HDFC Savings',
    exp_ba_balance: '12500.75',
    exp_ba_currency: 'INR',
    exp_ba_type: 'bank',
    exp_ba_icon: 'bank',
    exp_ba_color: '#4A90E2',
    exp_ba_is_primary: true,
    exp_ba_is_active: 1,
    exp_ba_is_deleted: false,
    exp_ba_created_at: '2025-07-01T10:00:00Z',
    exp_ba_updated_at: '2025-07-23T12:30:00Z',
  },
  {
    exp_ba_id: 2,
    exp_ba_user_id: 1,
    exp_ba_name: 'Paytm Wallet',
    exp_ba_balance: '850.50',
    exp_ba_currency: 'INR',
    exp_ba_type: 'wallet',
    exp_ba_icon: 'wallet',
    exp_ba_color: '#00BFA5',
    exp_ba_is_primary: false,
    exp_ba_is_active: 1,
    exp_ba_is_deleted: false,
    exp_ba_created_at: '2025-06-15T09:30:00Z',
    exp_ba_updated_at: '2025-07-23T12:30:00Z',
  },
  {
    exp_ba_id: 3,
    exp_ba_user_id: 1,
    exp_ba_name: 'Cash',
    exp_ba_balance: '2200',
    exp_ba_currency: 'INR',
    exp_ba_type: 'cash',
    exp_ba_icon: 'cash',
    exp_ba_color: '#FF9800',
    exp_ba_is_primary: false,
    exp_ba_is_active: 1,
    exp_ba_is_deleted: false,
    exp_ba_created_at: '2025-07-01T08:00:00Z',
    exp_ba_updated_at: '2025-07-23T12:30:00Z',
  },
  {
    exp_ba_id: 4,
    exp_ba_user_id: 1,
    exp_ba_name: 'ICICI Credit Card',
    exp_ba_balance: '-5200',
    exp_ba_currency: 'INR',
    exp_ba_type: 'credit',
    exp_ba_icon: 'credit-card',
    exp_ba_color: '#E91E63',
    exp_ba_is_primary: false,
    exp_ba_is_active: 1,
    exp_ba_is_deleted: false,
    exp_ba_created_at: '2025-05-20T11:00:00Z',
    exp_ba_updated_at: '2025-07-23T12:30:00Z',
  },
  {
    exp_ba_id: 5,
    exp_ba_user_id: 2,
    exp_ba_name: 'SBI Joint Account',
    exp_ba_balance: '18950.00',
    exp_ba_currency: 'INR',
    exp_ba_type: 'bank',
    exp_ba_icon: 'bank',
    exp_ba_color: '#3F51B5',
    exp_ba_is_primary: true,
    exp_ba_is_active: 1,
    exp_ba_is_deleted: false,
    exp_ba_created_at: '2025-06-01T10:00:00Z',
    exp_ba_updated_at: '2025-07-23T12:30:00Z',
  },
];

export const materialIconList: { [index: string]: string[] } = {
  Entertainment: [
    'sports-esports',
    'movie',
    'music-note',
    'event',
    'live-tv',
    'theaters',
    'local-bar',
    'nightlife',
    'celebration',
    'mic',
    'subscriptions',
  ],
  Finance: [
    'account-balance-wallet',
    'account-balance',
    'credit-card',
    'attach-money',
    'request-quote',
    'savings',
    'payments',
    'price-change',
    'price-check',
    'calculate',
  ],
  Food: [
    'restaurant',
    'local-dining',
    'fastfood',
    'icecream',
    'cake',
    'brunch-dining',
    'local-bar',
    'local-cafe',
    'dining',
    'takeout-dining',
    'local-grocery-store',
  ],
  General: [
    'category',
    'notes',
    'settings',
    'info',
    'edit',
    'delete',
    'help',
    'warning',
    'security',
    'dashboard',
  ],
  Medical: [
    'local-hospital',
    'medication',
    'medical-information',
    'healing',
    'monitor-heart',
    'masks',
    'local-pharmacy',
    'vaccines',
    'sick',
    'personal-injury',
    'pets',
  ],
  Shopping: [
    'shopping-cart',
    'store',
    'storefront',
    'loyalty',
    'shopping-bag',
    'local-mall',
    'local-offer',
    'card-giftcard',
    'qr-code-scanner',
    'payment',
  ],
  'People and Art': [
    'person',
    'group',
    'diversity-3',
    'face',
    'support-agent',
    'supervisor-account',
    'contacts',
    'child-care',
    'elderly',
    'volunteer-activism',
    'palette',
    'brush',
    'color-lens',
    'style',
    'edit-note',
    'animation',
    'gradient',
    'wallpaper',
    'design-services',
    'emoji-emotions',
  ],
  Travel: [
    'flight',
    'hotel',
    'commute',
    'beach-access',
    'hiking',
    'luggage',
    'map',
    'directions-car',
    'train',
    'departure-board',
    'airplane-ticket',
    'location-on',
  ],
  Bills: [
    'receipt-long',
    'receipt',
    'fact-check',
    'request-quote',
    'description',
    'payments',
    'attach-file',
  ],
  Utilities: [
    'lightbulb',
    'power',
    'water',
    'wifi',
    'router',
    'cable',
    'thermostat',
    'gas-meter',
    'solar-power',
    'battery-charging-full',
  ],
  Education: [
    'school',
    'menu-book',
    'auto-stories',
    'book',
    'backpack',
    'calculate',
    'science',
    'laptop-chromebook',
    'library-books',
    'draw',
  ],
  Work: [
    'work',
    'business-center',
    'engineering',
    'badge',
    'task-alt',
    'schedule',
    'meeting-room',
    'event-note',
  ],
  Transportation: [
    'directions-car',
    'directions-bus',
    'directions-bike',
    'commute',
    'electric-scooter',
    'train',
    'two-wheeler',
    'local-taxi',
    'pedal-bike',
    'airport-shuttle',
  ],
  Gifts: [
    'redeem',
    'card-giftcard',
    'loyalty',
    'volunteer-activism',
    'sentiment-satisfied',
    'celebration',
  ],
  Home: [
    'home',
    'weekend',
    'chair',
    'roofing',
    'kitchen',
    'bed',
    'bathroom',
    'light',
    'sensor-door',
    'foundation',
  ],
  Subscriptions: [
    'subscriptions',
    'smart-display',
    'stream',
    'tv',
    'video-library',
    'live-tv',
    'auto-awesome',
    'alarm-on',
  ],
};

export const customColors = [
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Sunset Orange', hex: '#FF7F50' },
  { name: 'Royal Purple', hex: '#7851A9' },
  { name: 'Deep Pink', hex: '#FF1493' },
  { name: 'Goldenrod', hex: '#DAA520' },
  { name: 'Coral', hex: '#FF6F61' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Sea Green', hex: '#2E8B57' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Midnight Blue', hex: '#191970' },
  { name: 'Peach', hex: '#FFDAB9' },
  { name: 'Mint', hex: '#98FF98' },
  { name: 'Amber', hex: '#FFBF00' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Rose Gold', hex: '#B76E79' },
  { name: 'Charcoal', hex: '#2E2E2E' },
  { name: 'Gunmetal', hex: '#2A3439' },
  { name: 'Slate Gray', hex: '#3E4C59' },
  { name: 'Deep Space Blue', hex: '#1B1F32' },
  { name: 'Midnight Navy', hex: '#1A1A2E' },
  { name: 'Rich Black', hex: '#202a53ff' },
  { name: 'Dark Indigo', hex: '#2C2C54' },
  { name: 'Carbon', hex: '#1D1E22' },
  { name: 'Jet', hex: '#343434' },
  { name: 'Onyx', hex: '#353839' },
  { name: 'Dark Chocolate', hex: '#3D2B1F' },
  { name: 'Ash Gray', hex: '#4B4B4B' },
  { name: 'Indigo Blue', hex: '#4F46E5' },
  { name: 'Coral Red', hex: '#FF6B6B' },
  { name: 'Emerald Green', hex: '#068836' },
  { name: 'Rose Red', hex: '#E63946' },
  { name: 'Green', hex: '#4CAF50' },
  { name: 'Purple', hex: '#7B61FF' },
  { name: 'Yellow', hex: '#FBBF24' },
  { name: 'Rose normal', hex: '#F472B6' },
  { name: 'Green light', hex: '#22C55E' },
    { name: 'Electric Indigo', hex: '#6F00FF' },
  { name: 'Flamingo Pink', hex: '#FC6C85' },
  { name: 'Lime Green', hex: '#32CD32' },
  { name: 'Cyber Yellow', hex: '#FFD300' },
  { name: 'Vivid Sky Blue', hex: '#00CCFF' },
  { name: 'Vermilion', hex: '#E34234' },
  { name: 'Tangerine', hex: '#F28500' },
  { name: 'Plum', hex: '#8E4585' },
  { name: 'Neon Blue', hex: '#1B03A3' },
  { name: 'Electric Purple', hex: '#BF00FF' },
  { name: 'Bright Teal', hex: '#00BFA6' },
  { name: 'Aqua Marine', hex: '#7FFFD4' },
  { name: 'Hot Magenta', hex: '#FF1DCE' },
  { name: 'Persian Green', hex: '#00A693' },
  { name: 'Pumpkin', hex: '#FF7518' },
  { name: 'Fire Red', hex: '#FF2400' },
  { name: 'Sapphire Blue', hex: '#0F52BA' },
  { name: 'Cosmic Purple', hex: '#5D3FD3' },
  { name: 'Shadow', hex: '#1E1E1E' },
  { name: 'Dark Matter', hex: '#101820' },
];

export const categoriesStatic = [
  {
    exp_tc_id: 1,
    exp_tc_label: 'Travel With Friends',
    exp_tc_icon: 'card-giftcard',
    exp_tc_user_id: 2,
    exp_tc_icon_bg_color: '#FFBF00',
    exp_tc_transaction_type: 2,
    exp_tc_sort_order: 1,
  },
  {
    exp_tc_id: 2,
    exp_tc_label: 'Restaurant',
    exp_tc_icon: 'restaurant',
    exp_tc_user_id: 1,
    exp_tc_icon_bg_color: '#FF6B6B',
    exp_tc_transaction_type: 2,
    exp_tc_sort_order: 1,
  },
  {
    exp_tc_id: 3,
    exp_tc_label: 'Salary',
    exp_tc_icon: 'attach-money',
    exp_tc_user_id: 1,
    exp_tc_icon_bg_color: '#22C55E',
    exp_tc_transaction_type: 1,
    exp_tc_sort_order: 2,
  },
  {
    exp_tc_id: 4,
    exp_tc_label: 'Medical',
    exp_tc_icon: 'local-hospital',
    exp_tc_user_id: 1,
    exp_tc_icon_bg_color: '#E63946',
    exp_tc_transaction_type: 2,
    exp_tc_sort_order: 2,
  },
  {
    exp_tc_id: 5,
    exp_tc_label: 'Online Shopping',
    exp_tc_icon: 'shopping-cart',
    exp_tc_user_id: 1,
    exp_tc_icon_bg_color: '#4F46E5',
    exp_tc_transaction_type: 2,
    exp_tc_sort_order: 2,
  },
  {
    exp_tc_id: 6,
    exp_tc_label: 'Others',
    exp_tc_icon: 'category',
    exp_tc_user_id: null,
    exp_tc_icon_bg_color: '#4F46E5',
    exp_tc_transaction_type: 1,
    exp_tc_sort_order: 0,
  },
];
